on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test CI
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12"
      - run: npm ci
      - run: npm test
